version: '3.7'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - net
    command: etcd
    environment:
      - ETCD_NAME=feature_toggle_etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://localhost:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=default=http://localhost:2380

  etcd-initializer:
    build:
      context: ./etcd
      dockerfile: Etcd-initializer.Dockerfile
    depends_on:
      - etcd
    restart: "no"
    networks:
      - net
    command: /bin/sh -c "cd var/etcd && ./load-default-values.sh initial-values-local.properties"

networks:
  net:
    external: false
